### ISSUE TITLE
Fix for 2.73 API change

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopology-contours#115]

**Comment by carter2422** [comment]
As reported here and other places. https://secure.helpscout.net/conversation/64861543/18465/

**Comment by sweenist** [comment]
Is this bug related, perchance to an IndexError like this?:

![retopterror_blender2 73](https://cloud.githubusercontent.com/assets/10158159/5888645/d10987ca-a3d5-11e4-9e92-86ef468955a1.PNG)

I finally got around to using this tool today. I'd dig into but don't want to duplicate someone else's efforts.

**Comment by carter2422** [comment]
Hey @sweenist, the error is due to using an older version of Contours in Blender 2.73; which introduced and API change. 

If you're using Contours 1.2.2 then please restart Blender before activating Contours.
