### ISSUE TITLE
Add_on is not Loading in 2.78c

### ISSUE THREAD

**Issue by 3Dline** [CGCookie/retopology-contours#116]
in Blender 2.78c got an error while try to setup. 
.
![error](https://cloud.githubusercontent.com/assets/27280059/24905299/29818b42-1ebc-11e7-8e90-c5ca2d255303.jpg)
.

**Comment by carter2422** [comment]
Hey @3Dline, the standalone Contours add-on is no longer maintained is almost certainly doesn't work in recent versions of Blender. 

Contours was merged into RetopoFlow a few years ago: https://blendermarket.com/products/retopoflow
https://github.com/cgcookie/retopoflow
