### ISSUE TITLE
the addon is not activating

### ISSUE THREAD

**Issue by SkeletalRaven** [CGCookie/retopology-contours#117]
hi, I tried to import the addon but it doesn't activate with blender 2.77 and 2.79

**Comment by vxlcoder** [comment]
Hi @SkeletalRaven!

Can you describe how you installed the add-on.

Is there anything reported when you try to enable it?  If you start Blender from the console, what is printed out in the console when you attempt to enable?

Also, which version of the tool are you using?  Contours is now a part of RetopoFlow, of which we are actively developing.  If you're still using the old Contours add-on, please switch to RetopoFlow.  Let us know if you have questions on this, so we can help!

**Comment by SkeletalRaven** [comment]
Yes I was using the old version it seems, I did not know about retopoflow, I used Contour retopo tool, just downloaded retopoflow and works perfect! thanks for the amazing tool, but still here is the error screen shot if you need it.

**Comment by SkeletalRaven** [comment]
I know this is not a report email and am sorry for sending that here but I don't know where else to send it, but I just used RetopoFlow, I teared a bit... so beautiful! :'( thank you so much for making such legendary tool!

**Comment by carter2422** [comment]
That's really great to hear @SkeletalRaven! 

Stay tuned for v2.0 :)
